### PR TITLE
Merged in Stack's work on pysnip in this branch

### PR DESCRIPTION
**Pull request by Ericson2314**

### CODE REVIEW

**Comment by infogulch** [comment]
Thanks for the pull request! Some thoughts:

I totally agree with using the buildandshoot server for the IP getter and master server, great replacements.

I'm not entirely happy that the `config.txt` and `*.pyc` files were added in the first place (even if they were later removed), but I can deal with it. (I guess they could be rebased out, but any existing PySnip repos would need a force updated.)

I'm not sure that `Pyspades -> PySnip revisions.` ( 375815e ) is a good idea for this repository. Actually, I'm not entirely sure why PySnip forked in the first place. 

As a whole, these look like good changes. It appears that it can't be merged automatically, so I'll have a look at the merge conflicts.

**Comment by infogulch** [comment]
It looks like the merge conflicts are trivial.

**Comment by Ericson2314** [comment]
I would just keep it in a new branch for a now. That's what I did. We can figure out how to merge later.

For the initial import from mercurial I just thought it would be best to keep his exact changes.

**Comment by infogulch** [comment]
This has been merged into the branch `BnS`. Closed.

**Pull request closed without merging**
