### PR TITLE
gun rebalancing for powerthirst edition

### PR DESCRIPTION
**Pull request by iamgreaser**
For 2013-05-10-00. Sonarpulse suggested I send this request to your repo as well.

### CODE REVIEW

**Comment by iamgreaser** [comment]
This might have been a bit too much, sorry.

**Comment by Ericson2314** [comment]
@iamgreaser you just set the target to protocol075 and not bns.

**Comment by noway** [comment]
Why there are iceball sources in feature_server for this PR? 😕

**Comment by Ericson2314** [comment]
Um, I think this predates iceball?

**Comment by noway** [comment]
Yeah, thought the same. Did the iceball changes got in the pr accidently?

**Pull request closed without merging**
